### ISSUE TITLE
A 404 error : The url is set correctly

### ISSUE THREAD

**Issue by sachintaware** [developerdynamo/crowdscore#2]
Client error: `GET https://api.crowdscores.com/api/competitions` resulted in a `404 NOT FOUND` response:

I am getting this error when I hit the desired route eg: `http://localhost/laravel-cashier/public/competitions`

I am using laravel 5.1 version of laravel.Tried to debug but the URL seems to be fine,not sure why the route hit is wrong. Can you point the mistake?

`Route::get('/matches',function(){
    $competitions = Crowdscore::competitions();
    var_dump($competitions);   
});`

**Comment by ilvalerione** [comment]
You are using a wrong endpoint.

In your URL missing api version (v1):

https://api.crowdscores.com/api/v1/competitions

instead of

https://api.crowdscores.com/api/competitions

Crowdsource API endpoint are in crowdsource.php in config/. You don't need to change it.

**Comment by sachintaware** [comment]
`/*
	 * Crowdscore API v1 endpoint
	 */
	"endpoint" => "https://api.crowdscores.com/api/v1",`

I haven't updated it but for some reason the its taking that URL. I also went to the methods but couldn't figure out where is the issue.

**Comment by ilvalerione** [comment]
If you insert this url in your browser: 

https://api.crowdscores.com/api/v1/competitions

the error is 403 and not 404.

403 error mean that you need to attach an api key to the request.
To obtain an API key you need to contact Crowdscore team.

**Comment by sachintaware** [comment]
I get your point @ilvalerione I am trying to debug why I am facing the issue! The URL is updated inernally somewhere.
 Will update with an elaborate description if I cannot fix it! Thank you for the replies.

**Comment by sachintaware** [comment]
@ilvalerione Could you please explain me the `buildUri`?

``` 
private function buildUri($uri, array $config)
    {   
       echo $uri;
        if (!isset($config['base_uri'])) {
            echo $uri instanceof UriInterface ? $uri : new Psr7\Uri($uri);
            return $uri instanceof UriInterface ? $uri : new Psr7\Uri($uri);
        }
        echo $config['base_uri'];
        echo Psr7\Uri::resolve(Psr7\uri_for($config['base_uri']), $uri);
        return Psr7\Uri::resolve(Psr7\uri_for($config['base_uri']), $uri);
    } 
```

I get the `$config['base_uri']` correct as _https://api.crowdscores.com/api/v1_

But the line `return Psr7\Uri::resolve(Psr7\uri_for($config['base_uri']), $uri);`

 returns this 

_https://api.crowdscores.com/api/competitions_

Not sure where exactly the url gets updated.

If I return a hard coded value, it works.
Something like this `return "https://api.crowdscores.com/api/v1/".$uri;`

**Comment by ilvalerione** [comment]
Are you using Guzzle 6?

In your composer:

"guzzlehttp/guzzle": "~6.0"

**Comment by sachintaware** [comment]
Yes here's the block
```
 "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "guzzlehttp/guzzle": "~6.0",
        "developerdynamo/crowdscore": "1.*"
    },
```
It's a fresh laravel 5.2.* install! Earlier I faced the same issue with 5.1 hence went with a new fresh install.
